export const menuItems = [
  {
    id: 0,
    name: 'Chicken Tenders',
    featured: true,
    amount: 1,
    type: 1,
  },
  {
    id: 1,
    name: 'Deep Fried Mac & Cheese',
    featured: true,
    amount: 1,
    type: 1,
  },
  {
    id: 2,
    name: 'Crab Cakes',
    featured: true,
    amount: 1,
    type: 1,
  },
  {
    id: 3,
    name: 'Lulabelles’s Sweet Truffle Fries',
    featured: true,
    amount: 1,
    type: 1,
  },
  {
    id: 4,
    name: 'Spinach & Cheese Dip',
    featured: true,
    amount: 1,
    type: 1,
  },
  {
    id: 5,
    name: 'Wings ( Honey Hot, Lemon Pepper, Cajun, BBQ)',
    featured: true,
    amount: 1,
    type: 1,
  },
  {
    id: 6,
    name: 'Lulabelle’s Potato Floats',
    featured: true,
    amount: 1,
    type: 1,
  },

  {
    id: 7,
    name: 'Signature Grill Fired Lamb Chops (served with 2 sides)',
    featured: true,
    amount: 1,
    type: 2,
    price: 2.99,
  },
  {
    id: 8,
    name: 'Southern Fried Lobster with Jumbo shrimp and Mac & Cheese',
    featured: true,
    amount: 1,
    type: 2,
    price: 2.99,
  },
  {
    id: 9,
    name: 'Salmon Dinner (Served with 2 sides)',
    featured: true,
    amount: 1,
    type: 2,
    price: 2.99,
  },
  {
    id: 10,
    name: 'Signature Ribeye Dinner (served with 2 sides)',
    featured: true,
    amount: 1,
    type: 2,
    price: 2.99,
  },
  {
    id: 11,
    name: 'Southern Fried Chicken Dinner (served with 2 sides)',
    featured: true,
    amount: 1,
    type: 2,
    price: 2.99,
  },

  {
    id: 12,
    name: 'Mediterranean salad',
    featured: true,
    amount: 1,
    type: 3,
  },
  {
    id: 13,
    name: 'Lulabelle’s Chef Salad',
    featured: true,
    amount: 1,
    type: 3,
  },
  {
    id: 14,
    name: 'Caesar Salad',
    featured: true,
    amount: 1,
    type: 3,
  },

  {
    id: 15,
    name: 'Mac & cheese',
    feature: true,
    amount: 1,
    type: 4,
  },
  {
    id: 16,
    name: 'Vegetables Medley',
    feature: true,
    amount: 1,
    type: 4,
  },
  {
    id: 17,
    name: 'Broccoli',
    feature: true,
    amount: 1,
    type: 4,
  },
  {
    id: 18,
    name: 'Southern Fried Rice',
    feature: true,
    amount: 1,
    type: 4,
  },
  {
    id: 19,
    name: 'Garlic Mashed Potatoes',
    feature: true,
    amount: 1,
    type: 4,
  },
  {
    id: 20,
    name: 'Side Caesar',
    feature: true,
    amount: 1,
    type: 4,
  },

  {
    id: 21,
    name: 'Strawberry Cheesecake',
    featured: true,
    amount: 1,
    type: 5,
  },
  {
    id: 22,
    name: 'Chocolate Cake',
    featured: true,
    amount: 1,
    type: 5,
  },
];
